language: cpp
compiler:
  - clang
  - gcc
script: make && make test
matrix:
  fast_finish: true
  exclude:
    - compiler: gcc
      os: osx
notifications:
  email: false
os:
  - linux
  - osx
sudo: false
